### ISSUE TITLE
API spec change for getExercises

### ISSUE THREAD

**Issue by stowellm** [uml-ubicomp-2016-spring/wrkr#10]
Old behavior: {<# exercises>, [timestamp1, timestamp2, ...]}
New behavior: {<#exercises>, [[timestamp1, complete?], [timestamp2, complete?]]}

**Comment by sergei-fomichev** [comment]
So is it something wrong with it?

**Comment by stowellm** [comment]
No, this is to remind me to change this on the app side.

**Comment by stowellm** [comment]
Resolved in upcoming commit.

**Comment by stowellm** [comment]
Resolved in upcoming commit.
