### ISSUE TITLE
Expire exercises and manipulate karma on mobile side

### ISSUE THREAD

**Issue by stowellm** [uml-ubicomp-2016-spring/wrkr#11]
After exercises expire, we should give a summary notification of exercises missed.

Karma score scheme:
- Starting value: 80
- Minimum: 0
- Maximum: 150
- Karma lost per missed exercise: -10
- Karma gained per exercise completed: +5

**Comment by stowellm** [comment]
See API spec addition that will be required: https://github.com/uml-ubicomp-2016-spring/wrkr/commit/129c270a826feb11ca45cbc7e1883b578693c95e

**Comment by sergei-fomichev** [comment]
Okay, I have already realised it when updated karma from the website. But it required a PUT request(instead of POST), because PUT is designed to modify existing data. So can you handle a PUT request? It's very similar to POST.

**Comment by stowellm** [comment]
I will see what I can do

**Comment by sergei-fomichev** [comment]
Alright. I will let you know when it's ready.

**Comment by sergei-fomichev** [comment]
All set. Can you also punish a user with 10 points as soon as I can't determine if the exercise completed on time or it's a delayed exercise completion.

**Comment by stowellm** [comment]
My plan for mobile end is pull the exercises down and check the timestamps of all the incomplete ones.  For each incomplete one that is 2 hours old, I will decrement their karma by 10 points and send you their new karma score if it changed.

Then on your side, the user should still see all incomplete exercises, including ones that expired that they've already lost 10 karma from. But they can still have the option to do the exercise so that they can redeem 5 points back for completing it.  I'm assuming you will do the +5 for completion.

**Comment by sergei-fomichev** [comment]
Perfect! Sounds good to me.

**Comment by stowellm** [comment]
The weblab instance is down right now.  E-mail sent to helpdesk.  Waiting for weblab to resume service before working on this feature request.
