### ISSUE TITLE
Smartwatch *still* insists on turning off the accelerometer

### ISSUE THREAD

**Issue by stowellm** [uml-ubicomp-2016-spring/wrkr#7]
I've tried reregistering wakelocks, reregistering the accelerometer... it refuses to stay alive.

Try the persistent notification hack that works on the smartphone to keep the accelerometer running.  And for that matter, use a persistent notification on the phone too to ensure to the API always remains running and ready to receive comm from the watch.

**Comment by gchenhub** [comment]
This person seems to use service/wake lock to get it work?

http://stackoverflow.com/questions/33224416/can-i-analyze-sensor-data-with-android-wear-in-background

**Comment by stowellm** [comment]
Thanks for the link.  This is what I have right now though: the watch registers a service that holds a partial wakelock.  Holding it indefinitely does not work, and re-registering it every 5 minutes does not work.  For test purposes, I will try a full wakelock - this won't be production-ready since it wll keep the screen on (and significantly damage the watch/battery over time).  I will also try a persistent notification (which if this works, would be acceptable).

**Comment by stowellm** [comment]
And as far as batching data collection: the getFifoCount returned by my watch is 0, i.e. it has 0 space for batched data.

**Comment by gchenhub** [comment]
If you really get stuck and want to move forward on this project, I guess we can try Pebble watch.

**Comment by stowellm** [comment]
See referenced issue.  After some testing by leaving the application open on the SettingsFragment, the watch is still recording data and has been successfully for the past hour.  The referenced issue is the likely cause.  Will re-open this issue iff that issue does not resolve this problem of accelerometer supposedly stopping.
